### ISSUE TITLE
How to use poses in realtime example?

### ISSUE THREAD

**Issue by montanaflynn** [franciscop/use-tensorflow#1]
When I change objects to poses I get this error:

```
react.development.js:172 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `App`. See https://fb.me/react-warning-keys for more information.
    in styled.div (created by App)
    in App
```

```js
  const ref = useCamera();
  const objects = useObjects(ref);
  const poses = usePoses(ref);
  return (
    <Container>
      <video ref={ref} autoPlay width="640" height="480" />
      {poses.map(({ left, top, width, height, label, score }) => (
        <Box
          left={left}
          top={top}
          width={width}
          height={height}
          label={label}
          color={score > 0.6 ? "blue" : "red"}
          score={score}
        />
      ))}
    </Container>
  );
```

**Comment by franciscop** [comment]
It's a *Warning* (not an error) that can be safely ignored. There's no *id* available to be used safely as key, so if you really want to do something about those warnings you can:
- Create a new random key per element
- Create a derived key with the properties you use (this will make things slower) as in `key={JSON.stringify({ left, top, width, height, label, score })}`
- Depending on your case, use the index as a key.

But be careful with the last one:
> Reorders can also cause issues with component state when indexes are used as keys. Component instances are updated and reused based on their key. If the key is an index, moving an item changes it. As a result, component state for things like uncontrolled inputs can get mixed up and updated in unexpected ways.

More info about the keys:
- https://reactjs.org/docs/lists-and-keys.html#keys
- https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318

**Comment by franciscop** [comment]
If that doesn't solve the problem please feel free to followup
